#!/usr/bin/env bash

# This script will be called when you push to remote repo and run update_setup
# You can add your personal checkes at the end

########## DO NOT CHANGE THIS PART ##########

repo_dir=$(git rev-parse --show-toplevel)

if [ ! -d "${repo_dir}/setup" ]; then
    mkdir -p ${repo_dir}/setup
fi

# Update update_setup
if [ ! -e "${repo_dir}/setup/update_setup" ]; then
    wget -q https://raw.githubusercontent.com/ThomasYeoLab/project_setup/main/update_setup -O ${repo_dir}/setup/update_setup
    chmod 755 ${repo_dir}/setup/update_setup
    git add ${repo_dir}/setup/update_setup
    git commit -m "Automatic commit: Add setup/update_setup" --no-verify
    echo "setup/update_setup added."
else
    wget -q https://raw.githubusercontent.com/ThomasYeoLab/project_setup/main/update_setup -O ${repo_dir}/setup/update_setup.new
    chmod 755 ${repo_dir}/setup/update_setup
    if diff ${repo_dir}/setup/update_setup.new ${repo_dir}/setup/update_setup >/dev/null; then
        rm ${repo_dir}/setup/update_setup.new
    else
        rm ${repo_dir}/setup/update_setup
        mv ${repo_dir}/setup/update_setup.new ${repo_dir}/setup/update_setup
        git add ${repo_dir}/setup/update_setup
        git commit -m "Automatic commit: Update setup/update_setup" --no-verify
        echo "setup/update_setup is updated."
    fi
fi

sh ${repo_dir}/setup/update_setup

########## CHANGE THIS PART ##########

# Add your personal checks here

exit 0

